namespace Domain.BusinessObjects;

public class Contact
{
    public required int Id { get; set; }
    public string? Abn { get; set; }
    public string? Accno { get; set; }
    public string? AccountsContactName { get; set; }
    public string? AccountsContactNumber { get; set; }
    public int? ActiveauditId { get; set; }
    public int? AddressBookId { get; set; }
    public string? AhContactName { get; set; }
    public string? AhContactumber { get; set; }
    public bool? BafterHoursKey { get; set; }
    public bool? BallowBillFast { get; set; }
    public bool? BallowEdi { get; set; }
    public bool? BallowN20direct { get; set; }
    public bool? BallowN20transit { get; set; }
    public bool? BallowQuickSwitch { get; set; }
    public bool? BallowUnderbondDirect { get; set; }
    public bool? BallowUnderbondTransit { get; set; }
    public bool? BallowViaRail { get; set; }
    public bool? Barchived { get; set; }
    public bool? BbillFastAllowRti { get; set; }
    public bool? BbillfastThresholdException { get; set; }
    public bool? BdgStorageWorkingDay { get; set; }
    public bool? BdoNotSchedule { get; set; }
    public bool? BdoNotTrade { get; set; }
    public bool? BdoNotTriangulate { get; set; }
    public bool? BdriverCanSelfDehire { get; set; }
    public bool? BdriverCanSelfLeg { get; set; }
    public bool? BediContact { get; set; }
    public bool? BgstExempt { get; set; }
    public bool? BholdDelivery { get; set; }
    public bool? BilsTrainSubsIdyFull { get; set; }
    public bool? BilsTrainSubsIdyMty { get; set; }
    public bool? BlclStorageWorkingDay { get; set; }
    public bool? BnoFuelLevy { get; set; }
    public bool? BonStopCredit { get; set; }
    public bool? BoogStorageWorkingDay { get; set; }
    public bool? BprEventCrossDelivery { get; set; }
    public bool? BreeferStorageWorkingDay { get; set; }
    public bool? BreqApproveCharge { get; set; }
    public bool? BresetPasswordActive { get; set; }
    public bool? BsendCwdEmail { get; set; }
    public bool? BsendEcpPickup { get; set; }
    public bool? BsendPodEmail { get; set; }
    public bool? BstorageIncludeDateIn { get; set; }
    public bool? BstorageIncludeDateOut { get; set; }
    public bool? BstorageUseCalenderDay { get; set; }
    public bool? BstorageWorkingDay { get; set; }
    public bool? BtreadCarefully { get; set; }
    public bool? BunderbondStorageWorkingDay { get; set; }
    public string? BillingEmail { get; set; }
    public string? BillingEmail1 { get; set; }
    public string? BillingEmail2 { get; set; }
    public int? Billingcontact { get; set; }
    public string? Board { get; set; }
    public string? ClinkedCompany { get; set; }
    public string? CargowiseAccNo { get; set; }
    public string? Ceo { get; set; }
    public string? ClientStatus { get; set; }
    public string? Comment { get; set; }
    public string? Company { get; set; }
    public decimal? DcycleThreshhold { get; set; }
    public decimal? DestRevenuePerContainer { get; set; }
    public decimal? DfullCycleTarget { get; set; }
    public decimal? DmtyCycleTarget { get; set; }
    public required string Defaultdoorsfacing { get; set; }
    public string? DefaultType { get; set; }
    public string? Department { get; set; }
    public string? DisplayName { get; set; }
    public DateTime? Dob { get; set; }
    public string? Donotsendemail { get; set; }
    public string? Donotsendmail { get; set; }
    public string? DriverNote { get; set; }
    public DateTime? DtArchived { get; set; }
    public DateTime? DtContactCreated { get; set; }
    public DateTime? DtDebtorBalanceUpDated { get; set; }
    public DateTime? DtDoNotTrade { get; set; }
    public DateTime? DtEstRevenueUpDated { get; set; }
    public DateTime? DtHoldDelivery { get; set; }
    public DateTime? DtOnStopCredit { get; set; }
    public DateTime? DtPasswordResetExpire { get; set; }
    public DateTime? DtPrEventCrossDelivery { get; set; }
    public DateTime? DtTreadCarefully { get; set; }
    public bool? EdiValiDated { get; set; }
    public string? EntityType { get; set; }
    public string? ExternalId { get; set; }
    public string? ExternalparentId { get; set; }
    public decimal? FdebtorBalance { get; set; }
    public decimal? Fdebtorbalance30 { get; set; }
    public decimal? Fdebtorbalance60 { get; set; }
    public decimal? Fdebtorbalance90 { get; set; }
    public string? FfFirstName { get; set; }
    public string? FfTitle { get; set; }
    public required bool Ffeligible { get; set; }
    public string? FfNumber { get; set; }
    public string? FfsurName { get; set; }
    public string? FirstName { get; set; }
    public required Guid SguId { get; set; }
    public string? HandlingContactName { get; set; }
    public string? HandlingContactNumber { get; set; }
    public string? Hrm { get; set; }
    public int? IarRep { get; set; }
    public int? IassignedRepAr { get; set; }
    public int? IassignedRepExportSemi { get; set; }
    public int? IassignedRepExportSl { get; set; }
    public int? IassignedRepImportSemi { get; set; }
    public int? IassignedRepImportSl { get; set; }
    public int? IassignedRepLocal { get; set; }
    public required int IclientInvoiceValIdationDay { get; set; }
    public int? IclientTierLevelId { get; set; }
    public int? IcorrZoneId { get; set; }
    public int? IcsRep { get; set; }
    public int? IcsRepExport { get; set; }
    public int? IcsRepExportSl { get; set; }
    public int? IcsRepImportSl { get; set; }
    public int? IcsRepLocal { get; set; }
    public int? IdefaultDeliveryJobNo { get; set; }
    public int? IdefaultEmptyTransitMethod { get; set; }
    public int? IdefaultTransitMethod { get; set; }
    public int? IdeliveryKpiId { get; set; }
    public int? IdgStorageFreeDay { get; set; }
    public int? IdoNotTradeBy { get; set; }
    public int? IgeoFenceId { get; set; }
    public int? IholdDeliveryBy { get; set; }
    public int? IilsRate { get; set; }
    public string? IinvoicePostCode { get; set; }
    public int? IlclStorageFreeDay { get; set; }
    public int? IoogStorageFreeDay { get; set; }
    public int? IprEventCrossDeliveryBy { get; set; }
    public int? IreeferStorageFreeDay { get; set; }
    public int? IreserveRepAr { get; set; }
    public int? IreserveRepExportSemi { get; set; }
    public int? IreserveRepExportSl { get; set; }
    public int? IreserveRepImportSemi { get; set; }
    public int? IreserveRepImportSl { get; set; }
    public int? IreserveRepLocal { get; set; }
    public int? IstopCreditBy { get; set; }
    public int? IstorageFreeDay { get; set; }
    public int? ItreadCarefullyBy { get; set; }
    public int? IunderbondStorageFreeDay { get; set; }
    public string? IndustryCode { get; set; }
    public string? Initial { get; set; }
    public string? Jobtitle { get; set; }
    public string? Lib { get; set; }
    public int? Linkedcontact { get; set; }
    public DateTime? LwDateTime { get; set; }
    public string? LwSessionId { get; set; }
    public string? LwUserName { get; set; }
    public string? MiddleName { get; set; }
    public int? Numemployee { get; set; }
    public string? OpenTime { get; set; }
    public string? OracleAccno { get; set; }
    public int? PaymentTermId { get; set; }
    public string? Primarycontact { get; set; }
    public string? Quoteeditcomment { get; set; }
    public int? Revision { get; set; }
    public string? SadminEmail { get; set; }
    public string? SarchivedBy { get; set; }
    public string? SassignedCompany { get; set; }
    public string? SbillFastMethod { get; set; }
    public string? SbillingContactName { get; set; }
    public string? SbillingPaymentTerm { get; set; }
    public string? SbillingPhone { get; set; }
    public string? ScompanyGroup { get; set; }
    public string? ScwdEmailAddress { get; set; }
    public string? SdisplayColour { get; set; }
    public string? SdisplayColourText { get; set; }
    public string? SinvoiceAddress { get; set; }
    public string? SinvoiceCountryCode { get; set; }
    public string? SinvoiceEmail { get; set; }
    public string? SinvoiceState { get; set; }
    public string? SinvoiceSuburb { get; set; }
    public string? SkeyLocation { get; set; }
    public string? SkeySerial { get; set; }
    public string? SpaymentTerm { get; set; }
    public string? SpodEmailAddress { get; set; }
    public string? SsendEcpPickupEmailAddress { get; set; }
    public string? StradingAs { get; set; }
    public string? Safety { get; set; }
    public string? SalesContactName { get; set; }
    public string? SalesContactNumber { get; set; }
    public int? SalesContactStevensonId { get; set; }
    public string? Salutation { get; set; }
    public string? SecindustryCode { get; set; }
    public string? SemiExportContactName { get; set; }
    public string? SemiExportContactNumber { get; set; }
    public int? SemiExportContactStevensonId { get; set; }
    public string? SemiExportEmail { get; set; }
    public string? SemiImportContactName { get; set; }
    public string? SemiImportContactNumber { get; set; }
    public int? SemiImportContactStevensonId { get; set; }
    public string? SemiImportEmail { get; set; }
    public string? Seminar { get; set; }
    public string? SiteReqNote { get; set; }
    public string? SlAccountsEmail { get; set; }
    public string? SlExportContactName { get; set; }
    public string? SlExportContactNumber { get; set; }
    public int? SlExportContactStevensonId { get; set; }
    public string? SlExportEmail { get; set; }
    public string? SlHandlingEmail { get; set; }
    public string? SlImportContactName { get; set; }
    public string? SlImportContactNumber { get; set; }
    public int? SlImportContactStevensonId { get; set; }
    public string? SlImportEmail { get; set; }
    public string? SlSalesEmail { get; set; }
    public string? Spclub { get; set; }
    public string? SurName { get; set; }
    public string? Title { get; set; }
    public DateTime? VerifyDateTime { get; set; }
    public string? VerifysessionId { get; set; }
    public string? VerifyuserName { get; set; }
    public string? Vip { get; set; }
    public string? Website { get; set; }
    public string? XmlCompanyName { get; set; }

    // Backwards compatibility properties
    public string AssignedCompany { get; set; } = string.Empty;
    public string CompanyGroup { get; set; } = string.Empty;
    
    // Navigation properties
    public ICollection<Membership> Memberships { get; set; } = new List<Membership>();
    public AssociatedCompany? AssociatedCompany { get; set; }
}